### ISSUE TITLE
Does not work with latest cpfw appliance

### ISSUE THREAD

**Issue by Savemech** [felixb/cpfw-login#4]
./cpfw-login --url="https://fancy.fqdn.here.com/connect/" --user="jonh" --password="jonhdoeindabest" --insecure=true 
2016/10/17 12:59:57 Connecting to: https://fancy.fqdn.here.com/connect/
2016/10/17 12:59:58 Logged in as john
2016/10/17 12:59:59 unexpected error: Session setup failed: authenticated: true, end of session:

**Comment by felixb** [comment]
well, I need you to fix it yourself and send a PR. I'm unable to get my hands one any other version of that damn firewall.

**Comment by Savemech** [comment]
that would be great, if i was good as you in golang (:
